---
  - hosts: all
    handlers:
      - name: restart mysql
        service:
          name: mysql
          state: restarted
        become: yes
      - name: restart wildfly
        service:
          name: wildfly
          state: restarted
        become: yes
    tasks:
      - name: 'Downloading and Installing MySQL Server 5.7'
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - python-mysqldb
          - mysql-server-5.7
        become: yes

      - name: 'Downloading and Installing Open JDK 11'
        apt:
          name: openjdk-11-jdk
          state: present
        become: yes

      - name: 'Downloading and Installing Expect'
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - expect
          - python-pexpect
        become: yes

      - name: 'Creating [store] database'
        mysql_db:
          name: store
          state: present
        become: yes

      - name: 'Creating [store] database user'
        mysql_user:
          name: softcube
          password: Brasil@77!
          priv: store.*:ALL
          host: '%'
          state: present
        become: yes

      - name: 'Providing external access to MySQL Server 5.7'
        copy:
          src: ../mysql/mysqld.cnf
          dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        become: yes
        notify:
          - restart mysql

      - name: 'Downloading Wildfly 17.0.1.Final'
        get_url:
          url: https://download.jboss.org/wildfly/17.0.1.Final/wildfly-17.0.1.Final.tar.gz
          dest: /tmp/wildfly-17.0.1.Final.tar.gz

      - name: 'Extracting Wildfly 17.0.1.Final'
        unarchive:
          src: /tmp/wildfly-17.0.1.Final.tar.gz
          dest: /bin/
          remote_src: yes
          owner: root
          group: root
          mode: 0744
        become: yes

      - name: 'Removing Wildfly 17.0.1.Final directory'
        file:
          path: /bin/wildfly
          state: absent
        become: yes

      - name: 'Renaming the Wildfly 17.0.1.Final directory'
        command: mv /bin/wildfly-17.0.1.Final /bin/wildfly
        become: yes

      - name: 'Configuring Wildfly 17.0.1.Final'
        copy:
          src: ../wildfly/standalone.xml
          dest: /bin/wildfly/standalone/configuration/standalone.xml
          owner: root
          group: root
          mode: 0744
        become: yes

      - name: 'Creating MySQL 5.7 module folder at Wildfly 17.0.1.Final'
        file:
          path: /bin/wildfly/modules/system/layers/base/com/mysql/main
          state: directory
        become: yes

      - name: 'Providing MySQL 5.7 module to Wildfly 17.0.1.Final'
        copy:
          src: ../wildfly/mysql-module/module.xml
          dest: /bin/wildfly/modules/system/layers/base/com/mysql/main/
          owner: root
          group: root
          mode: 0744
        become: yes

      - name: 'Providing MySQL 5.7 Java Connector to Wildfly 17.0.1.Final'
        copy:
          src: ../wildfly/mysql-module/mysql-connector-java-5.1.47.jar
          dest: /bin/wildfly/modules/system/layers/base/com/mysql/main/mysql-connector-java-5.1.47.jar
          owner: root
          group: root
          mode: 0744
        become: yes

      - name: 'Creating Wildfly 17.0.1.Final initialization script'
        copy:
          src: ../wildfly/wildfly.sh
          dest: /bin
        become: yes

      - name: 'Configuring Wildfly 17.0.1.Final as a service'
        copy:
          src: ../wildfly/wildfly.service
          dest: /etc/systemd/system/wildfly.service
          owner: root
          group: root
          mode: 0744
        become: yes

      - name: 'Reloading Linux Daemon'
        shell: systemctl daemon-reload
        become: yes
        notify:
          - restart wildfly

      - name: 'Creating Wildfly 17.0.1.Final Administrator User'
        shell: sh /bin/wildfly/bin/add-user.sh -u softcube-admin -p Brasil@77! -s -e
        become: yes
