---
- name: 'Downloading and Installing MySQL Server 5.7'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server-5.7
  become: yes

- name: 'Creating [store] database'
  mysql_db:
    name: "{{ db_name }}"
    state: present
  become: yes

- name: 'Creating [store] database user'
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ item }}"
    state: present
  with_items:
    - "{{ db_allowable_hosts }}"
  become: yes

- name: 'Providing external access to MySQL Server 5.7'
  template:
    src: roles/mysql_server/templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  notify:
    - restart mysql
